-- MOVED — this file is no longer the source of truth.
--
-- The schema now lives as a versioned migration:
--
--     supabase/migrations/20260813000000_init_sync_schema.sql
--
-- so that local and production can never drift. The workflow (docs/supabase-setup.md):
--
--     npm run db:start     boot the local Postgres + auth stack in Docker
--     npm run db:reset     wipe and replay every migration locally
--     npm run db:diff      capture Studio changes as a new migration file
--     npm run db:push      apply pending migrations to the hosted project
--
-- Change the schema by adding a NEW migration, never by editing an applied one:
-- a migration that has already run somewhere is history, and rewriting it makes
-- the two environments disagree in ways that only show up in production.
