-- Daily Challenge leaderboards: one global board per age division, plus
-- invite-only boards (family, class, friends).
--
-- Two rules shape everything below, and they are why this is not just a
-- "select * from scores order by score desc":
--
--   1. A child's real name never leaves the household. The global board is
--      pseudonymous for EVERYONE — the `alias` column is generated by Postgres
--      from the profile id, so a tampered client cannot smuggle a real name
--      into a stranger-visible list. Real display names appear only on boards
--      someone was invited to.
--
--   2. The client never states its own score. `score` is a generated column
--      computed from wpm/acc/rhythm by the same formula as scoreFor() in
--      src/lib/challenge.ts, and those three inputs are CHECK-clamped to human
--      ranges. This is integrity, not anti-cheat: a determined user can still
--      type slowly and report a plausible-but-false wpm, because the run itself
--      happens in their browser. Treat the board as social, not competitive
--      ranking with stakes.
--
-- Reads of other people's rows go exclusively through the security-definer
-- functions at the bottom. RLS on the table itself stays "own rows only", so
-- there is no path to a raw scan of every learner in the product.

-- ---------------------------------------------------------------------------
-- Pseudonyms
-- ---------------------------------------------------------------------------
-- IMMUTABLE and pure so it can back a generated column. md5 of the profile id
-- gives a stable handle that survives a rename: the same learner is the same
-- rival on the board every day, without ever exposing who they are.
create or replace function keytopia_alias(p_profile_id text)
returns text
language sql
immutable
as $$
  select (array[
      'Swift','Bright','Calm','Bold','Quiet','Clever','Sunny','Brave',
      'Steady','Nimble','Cosmic','Merry'
    ])[(('x' || substr(md5(p_profile_id), 1, 4))::bit(16)::int % 12) + 1]
    || (array[
      'Otter','Comet','Falcon','Marble','Lantern','Compass','Puffin','Willow',
      'Ember','Harbor','Meadow','Kestrel'
    ])[(('x' || substr(md5(p_profile_id), 5, 4))::bit(16)::int % 12) + 1]
    || substr(md5(p_profile_id), 9, 2);
$$;

-- ---------------------------------------------------------------------------
-- Scores
-- ---------------------------------------------------------------------------
-- One row per learner per day: the day's best. `day_key` is the client's local
-- calendar day (YYYY-MM-DD) rather than a server date, because "today's
-- challenge" is defined by the learner's own midnight, not UTC's.
create table if not exists daily_scores (
  day_key      text not null check (day_key ~ '^\d{4}-\d{2}-\d{2}$'),
  profile_id   text not null references profiles (id) on delete cascade,
  owner        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  age_group    text not null check (age_group in ('kid', 'teen', 'adult')),
  mode         text not null check (mode in ('speed', 'accuracy', 'rhythm')),

  -- What the client may state. The bounds are what a human hand can produce;
  -- anything outside them is a bug or a forgery, and either way it must not
  -- land on a board where it would sit permanently at rank 1.
  wpm          real not null check (wpm >= 0 and wpm <= 250),
  acc          real not null check (acc >= 0 and acc <= 100),
  rhythm       real not null default 0 check (rhythm >= 0 and rhythm <= 100),

  -- What the client may not. Mirrors scoreFor() in src/lib/challenge.ts —
  -- if that formula changes, add a migration that changes this too, or the
  -- board and the results screen will quietly disagree.
  score        integer not null generated always as ((
    case mode
      when 'accuracy' then round(acc * 10 + least(wpm, 40))
      when 'rhythm'   then round(rhythm * 8 + wpm + acc)
      else                 round((case when acc < 92 then wpm * 0.6 else wpm end) * 10 + acc)
    end)::integer) stored,

  -- Never NULL, never a real name on the global board.
  alias        text not null generated always as (keytopia_alias(profile_id)) stored,
  -- Shown only on boards the learner was invited to.
  display_name text not null check (length(display_name) between 1 and 40),
  avatar       text not null check (length(avatar) <= 64),

  submitted_at timestamptz not null default now(),
  primary key (day_key, profile_id)
);

-- The board query is "today, one division, best first". Covering it as an index
-- keeps the global board a single index scan as the table grows.
create index if not exists daily_scores_board
  on daily_scores (day_key, age_group, score desc);
create index if not exists daily_scores_by_profile
  on daily_scores (profile_id);

-- ---------------------------------------------------------------------------
-- Invite-only boards
-- ---------------------------------------------------------------------------
create table if not exists boards (
  id          uuid primary key default gen_random_uuid(),
  -- Short, shareable, and case-insensitively unique. Generated server-side in
  -- create_board() so it cannot be chosen (and so nobody claims 'FAMILY').
  code        text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  name        text not null check (length(name) between 1 and 40),
  -- Social boards only. A classroom is deliberately NOT one of these: KeyTopia
  -- Classroom (20260814121000_classrooms.sql) is a separate teacher surface
  -- with a roster, assignments and peer-hidden scores, and it has its own join
  -- codes. Two "join with a code" flows both called a class would read as one
  -- feature to a family, so the word belongs to that product, not this one.
  kind        text not null check (kind in ('family', 'friends')),
  created_by  uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now()
);

create table if not exists board_members (
  board_id    uuid not null references boards (id) on delete cascade,
  profile_id  text not null references profiles (id) on delete cascade,
  owner       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  joined_at   timestamptz not null default now(),
  primary key (board_id, profile_id)
);
create index if not exists board_members_by_profile on board_members (profile_id);

-- A policy on board_members that asks "is the caller a member of this board?"
-- would query board_members and recurse. SECURITY DEFINER breaks the cycle by
-- stepping outside RLS for that one lookup.
create or replace function is_board_member(p_board_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from board_members m
    where m.board_id = p_board_id and m.owner = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
alter table daily_scores  enable row level security;
alter table boards        enable row level security;
alter table board_members enable row level security;

-- Deliberately *not* "select to everyone". Cross-learner reads happen only
-- through the functions below, which decide what is safe to reveal.
drop policy if exists "own daily scores" on daily_scores;
create policy "own daily scores" on daily_scores
  for all to authenticated
  using (owner = auth.uid())
  with check (
    owner = auth.uid()
    and exists (select 1 from profiles p where p.id = profile_id and p.owner = auth.uid())
  );

-- Anonymous sessions exist in this project so a child can claim a classroom
-- seat without an email (20260814121000_classrooms.sql). They are the same
-- `authenticated` role as a real household, which means every policy above
-- would otherwise treat a throwaway identity as a signed-up member: mint an
-- anonymous session, create a profile, post 249 wpm, and that row sits at the
-- top of a global division forever. RESTRICTIVE (not permissive) so it ANDs
-- with the ownership policy rather than offering a second way in.
--
-- Writes only. Reading stays open, so a child on a school seat can still watch
-- the board — they just cannot compete on a board of strangers, which is the
-- same promise the Family page already makes.
drop policy if exists "no anonymous scores" on daily_scores;
create policy "no anonymous scores" on daily_scores
  as restrictive
  for all to authenticated
  using (true)
  with check (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

drop policy if exists "boards you belong to" on boards;
create policy "boards you belong to" on boards
  for select to authenticated
  using (created_by = auth.uid() or is_board_member(id));

drop policy if exists "creator manages board" on boards;
create policy "creator manages board" on boards
  for all to authenticated
  using (created_by = auth.uid()) with check (created_by = auth.uid());

-- Members see the roster of boards they are on; they may only add/remove their
-- own profiles, so nobody can enrol someone else's child in their board.
drop policy if exists "roster of your boards" on board_members;
create policy "roster of your boards" on board_members
  for select to authenticated
  using (is_board_member(board_id));

drop policy if exists "manage your own membership" on board_members;
create policy "manage your own membership" on board_members
  for all to authenticated
  using (owner = auth.uid())
  with check (
    owner = auth.uid()
    and exists (select 1 from profiles p where p.id = profile_id and p.owner = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Board reads
-- ---------------------------------------------------------------------------
-- Global: pseudonymous, one age division, today only. `you` lets the client
-- highlight the caller's row without being told which profile ids exist.
create or replace function daily_board_global(
  p_day text,
  p_age text,
  p_profile_id text default null,
  p_limit int default 20
)
returns table (rank int, name text, avatar text, wpm real, acc real, score int, you boolean)
language sql
stable
security definer
set search_path = public
as $$
  with ranked as (
    select
      rank() over (order by s.score desc, s.submitted_at asc)::int as rank,
      s.alias as name,
      -- A kid's chosen avatar is part of how they present themselves, so it is
      -- withheld from strangers too; the board draws a neutral one instead.
      case when s.age_group = 'kid' then '' else s.avatar end as avatar,
      s.wpm, s.acc, s.score,
      (s.profile_id is not distinct from p_profile_id) as you
    from daily_scores s
    where s.day_key = p_day and s.age_group = p_age
  )
  -- Top N, plus the caller's own row when it finished outside it: a board that
  -- silently omits you reads as "you did not count".
  select * from ranked where rank <= greatest(p_limit, 1)
  union
  select * from ranked where you
  order by rank;
$$;

-- Invited boards show real names, because everyone on them was invited by
-- someone in the household. Membership is re-checked here rather than trusted
-- from the client — this function runs as definer and would otherwise be an
-- open read of any board's scores.
create or replace function daily_board_group(
  p_day text,
  p_board_id uuid,
  p_profile_id text default null,
  p_limit int default 50
)
returns table (rank int, name text, avatar text, wpm real, acc real, score int, you boolean)
language sql
stable
security definer
set search_path = public
as $$
  select
    rank() over (order by s.score desc, s.submitted_at asc)::int,
    s.display_name,
    s.avatar,
    s.wpm, s.acc, s.score,
    (s.profile_id is not distinct from p_profile_id)
  from daily_scores s
  join board_members m on m.profile_id = s.profile_id and m.board_id = p_board_id
  where s.day_key = p_day
    and is_board_member(p_board_id)
  order by s.score desc, s.submitted_at asc
  limit greatest(p_limit, 1);
$$;

-- ---------------------------------------------------------------------------
-- Board membership
-- ---------------------------------------------------------------------------
create or replace function create_board(p_name text, p_kind text, p_profile_id text)
returns table (id uuid, code text, name text, kind text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_id   uuid;
begin
  -- SECURITY DEFINER runs as the owner and therefore bypasses RLS entirely, so
  -- the restrictive policy on daily_scores does nothing here. The anonymous
  -- check has to be repeated in the body of every definer function.
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'anonymous sessions cannot create boards';
  end if;
  if not exists (select 1 from profiles p where p.id = p_profile_id and p.owner = auth.uid()) then
    raise exception 'profile does not belong to this account';
  end if;

  -- Ambiguous glyphs (0/O, 1/I) are left out: these codes get read aloud and
  -- typed by children.
  loop
    v_code := (
      select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
                               (random() * 31)::int + 1, 1), '')
      from generate_series(1, 6)
    );
    exit when not exists (select 1 from boards b where b.code = v_code);
  end loop;

  insert into boards (code, name, kind) values (v_code, p_name, p_kind)
  returning boards.id into v_id;

  insert into board_members (board_id, profile_id) values (v_id, p_profile_id);

  return query
    select b.id, b.code, b.name, b.kind from boards b where b.id = v_id;
end;
$$;

create or replace function join_board(p_code text, p_profile_id text)
returns table (id uuid, code text, name text, kind text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  -- As in create_board: definer rights mean RLS is not doing this for us.
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'anonymous sessions cannot join boards';
  end if;
  if not exists (select 1 from profiles p where p.id = p_profile_id and p.owner = auth.uid()) then
    raise exception 'profile does not belong to this account';
  end if;

  select b.id into v_id from boards b where b.code = upper(trim(p_code));
  if v_id is null then
    raise exception 'no board with that code';
  end if;

  insert into board_members (board_id, profile_id) values (v_id, p_profile_id)
  on conflict (board_id, profile_id) do nothing;

  return query
    select b.id, b.code, b.name, b.kind from boards b where b.id = v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
-- As in the sync schema: RLS decides which rows, grants decide whether the role
-- may address the table at all, and both gates must be open.
grant select, insert, update, delete on table daily_scores  to authenticated;
grant select                        on table boards         to authenticated;
grant select, insert, delete        on table board_members  to authenticated;

-- Postgres grants EXECUTE to PUBLIC on every newly created function, and PUBLIC
-- includes `anon`. Granting to `authenticated` alone therefore changes nothing —
-- the door was already open, and a signed-out visitor could read the whole
-- global board. Revoke first, then grant; the order is the entire point.
revoke execute on function daily_board_global(text, text, text, int) from public;
revoke execute on function daily_board_group(text, uuid, text, int)  from public;
revoke execute on function create_board(text, text, text)            from public;
revoke execute on function join_board(text, text)                    from public;
revoke execute on function is_board_member(uuid)                     from public;
revoke execute on function keytopia_alias(text)                      from public;

grant execute on function daily_board_global(text, text, text, int) to authenticated;
grant execute on function daily_board_group(text, uuid, text, int)  to authenticated;
grant execute on function create_board(text, text, text)            to authenticated;
grant execute on function join_board(text, text)                    to authenticated;
grant execute on function is_board_member(uuid)                     to authenticated;
-- keytopia_alias MUST be executable by the inserting role. A generated column
-- is evaluated with the privileges of whoever runs the INSERT, not the table
-- owner, so revoking this from `authenticated` does not hide the function —
-- it makes every score submission fail outright with "permission denied for
-- function keytopia_alias". Revoked from PUBLIC above, granted back here.
grant execute on function keytopia_alias(text)                      to authenticated;

-- `anon` gets nothing: signed-out visitors never appear on, or read, a board.
